styled all components with style guidelines provided
mrnadaara/Math-Magicians-Calculator pull request #5
Opened 2020-06-07 13:52 UTC by mrnadaara

Aim of this PR was to align and style components to look like a typical calculator.

Following components were styled using Sass and display flex:
- App
- Button
- ButtonPanel
- Display

2020-06-08 14:33 UTC, AdnanAfsari requested changes
**Status: Changes Required**

Hello @mrnadaara ✋ 

Everything looks perfect but just a minor fix.

- [ ] At the end of this milestone, the styled version of the calculator should look like this [Calculator](https://github.com/microverseinc/project-react-calculator/blob/master/images/calculator.png).Please make necessary changes required.

- [ ] Position the Calculator in the middle of the screen so It would look better.

Please submit for another review after making changes.

Happy Coding
Adnan Afsari

2020-06-09 01:57 UTC, bellom approved these changes
#### Hi @mrnadaara 

### Kindly make the little changes and move on to the next milestone 👍 

**_Good luck in the next milestone :slightly_smiling_face:_** 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-09 01:57 UTC, bellom commented on src/components/ButtonPanel/ButtonPanel.jsx
>        <Button name="X" />
I trust you can do this before merging
Kindly make this big `X` a small one `x`

2020-06-09 01:57 UTC, bellom commented on src/components/ButtonPanel/ButtonPanel.jsx
> +      <Button name="/" />
I trust you can do this 👇  before merging.
Kindly make use of this well-known division sign `÷` on a calculator.

If you have doubts, kindly check the requirement the previous reviewer shared with you.
Click on the `calculator` link

2020-06-09 12:07 UTC, merged